### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by NgoHuy** [sorbo/tcpcrypt#19]
I use `Archlinux` and got the error 

> Initializing...
> tcpcryptd: tcpcrypt.c:116: do_add_ciphers: Assertion `p + sz <= (uint8_t*) speclen' failed.
> Aborted (core dumped)

`tcpcryptd` failed to start

**Comment by AJones394** [comment]
I have the same above problem, on Systemd Arch Linux the problem exists, With older ArchLinux with rc.conf it works fine.

**Comment by grahama** [comment]
Same problem on Fedora 19:

Initializing...
tcpcryptd: tcpcrypt.c:116: do_add_ciphers: Assertion `p + sz <= (uint8_t*) speclen' failed.
Aborted

**Comment by StrangeTcy** [comment]
Same issue with Ubuntu 12.04, although all the previous steps worked fine.
