### ISSUE TITLE
nfq_unbind_pf(): Invalid argument

### ISSUE THREAD

**Issue by intgr** [sorbo/tcpcrypt#2]
Yesterday someone reported a problem on Arch Linux forums where the nfq_unbind_pf() function fails with "Invalid argument", on Arch Linux: https://bbs.archlinux.org/viewtopic.php?pid=839012#p839012

After digging a bit further, I found several reports of the same problem with other software, the ndq_unbind_pf() function returning EINVAL. The reports seem to be only specific to 2.6.23, but unfortunately I don't know what kernel version the reporter is running.
1. http://developer.berlios.de/bugs/?func=detailbug&bug_id=12156&group_id=2509
2. http://copilotconsulting.com/mail-archives/snort-users.2008/msg01036.html

However it was suggested on the netfilter list that the return value of nfq_unbind_pf() should be ignored in the first place? http://www.spinics.net/lists/netfilter/msg42063.html
People seem to have taken their advice: http://software.inl.fr/trac/changeset/6956

So, I don't know if ignoring nfq_unbind_pf() return is still a good idea or not -- maybe it's been fixed in newer kernels. I'm just putting this out here, hopefully you know better than me.

**Comment by sorbo** [comment]
hey thanks for testing & reporting bugs.

I read the code and i don't see how ignoring the error will solve it - i think it'll barf on the next (bind) call if the error is ignored.  Anyway, he can try to ignore the error - just replace the err() call with a printf() on line 112 of user/tcpcrypt/linux.c and see how far he gets.

Possibly, the issue could be that he's got the "ip_queue" module loaded which conflicts with nfqueue.  Can he rmmod ip_queue and grep CONFIG_IP_NF_QUEUE from his kernel config to make sure it's not built in?

**Comment by intgr** [comment]
According to the configuration here:
http://code.toofishes.net/cgit/dan/eee.git/tree/kernel-eee/kernelconfig
 CONFIG_IP_NF_QUEUE is not set

**Comment by sorbo** [comment]
yeah but even:

<pre>CONFIG_NETFILTER_NETLINK_QUEUE is not set</pre>


Is he running that actual conf or did he tweak it?  Maybe he enabled both if he had to tweak.

It'd be great if he can confirm that removing err() fixes stuff, or what his current kernel confguration, version and patches are.

**Comment by intgr** [comment]
Right, I invited him to take part of this discussion here :)

**Comment by faelar** [comment]
Hi,

I do not compile the kernel, I download it from the [eee] repository so no change to the kernelconfig.

Here the output of lsmod (sorry for the formating) :

Module                  Size  Used by
ipv6                  171070  8 
nf_conntrack_ipv4       7130  1 
nf_defrag_ipv4           739  1 nf_conntrack_ipv4
xt_conntrack            1765  1 
nf_conntrack           33922  2 nf_conntrack_ipv4,xt_conntrack
iptable_filter           776  1 
ip_tables               6976  1 iptable_filter
x_tables                8532  3 xt_conntrack,iptable_filter,ip_tables

I will try to remove err() as you suggested.

EDIT : removed the err() call, and then the whole condition (line 111 and 112), it stills output the same error, namely tcpcryptd: nfq_unbind_pf(): Invalid argument.

I'd like to add that it only displays such a message when I try to open a website in my browser (or when my IM do requests in the background).

**Comment by sorbo** [comment]
the problem, i think, is that you don't have nfnetlink_queue at all.  It's not listed as a module and it's not compiled into your kernel if you're using the kernel conf intgr linked to.

You need to recompile your kernel to include nfnetlink_queue as a module.

**Comment by Futureknows** [comment]
Similar problem in Fedora 27:

`$ tcpcryptd
Initializing...
Reading random seed from /dev/urandom 
tcpcryptd: nfq_unbind_pf(): Operation not permitted
==== DUMPING STATE ====
=======================`



When I try to start service:

`$ systemctl start tcpcrypt
Failed to start tcpcrypt.service: Unit tcpcrypt.service not found.
`
